config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "dashboard#index"
    resources :brands, only: [ :index, :new, :create, :destroy ] do
      resources :models, only: [ :new, :create, :destroy ]
      collection do
        delete "delete_all"
      end
    end
  end

  resources :brands do
    resources :models
  end

  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  root "brands#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :models, dependent: :destroy
  validates :name, presence: true
end

app/models/model.rb
class Model < ApplicationRecord
  attr_accessor :brand_name
  belongs_to :brand
  validates :name, :year, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    role == "admin"
  end
end

app/controllers/admin/models_controller.rb
module Admin
  class ModelsController < ApplicationController
    before_action :authenticate_user!
    before_action :admin_only
    before_action :set_brand

    def new
      @model = @brand.models.new
    end

    def create
      @model = @brand.models.new(model_params)
      if @model.save
        redirect_to admin_root_path, notice: "Model was successfully created."
      else
        render :new
      end
    end

    def destroy
      @model = @brand.models.find(params[:id])
      @model.destroy
      redirect_to admin_root_path, notice: "Model was successfully destroyed."
    end

    private

    def set_brand
      @brand = Brand.find(params[:brand_id])
    end

    def model_params
      params.require(:model).permit(:name, :year)
    end

    def admin_only
      if current_user.nil? || !current_user.admin?
        redirect_to(root_path, alert: "Not authorized")
      end
    end
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :user_only, only: [ :edit, :update ]
  before_action :admin_only, only: [ :new, :create, :destroy ]
  before_action :set_model, only: %i[ show edit update destroy ]
  before_action :set_brand

  # GET /brands/:brand_id/models or /brands/:brand_id/models.json
  def index
    @models = Model.where(brand_id: params[:brand_id])
    @models.each do |model|
      model.brand_name = Brand.find(model.brand_id).name
    end
  end

  # GET /brands/:brand_id/models/1 or /brands/:brand_id/models/1.json
  def show
    @model = Model.find(params[:id])
    @brand = Brand.find(@model.brand_id)
    @model.brand_name = @brand.name
  end

  # GET /brands/:brand_id/models/new
  def new
    @model = Model.new
  end

  # GET /brands/:brand_id/models/1/edit
  def edit
  end

  # POST /brands/:brand_id/models or /brands/:brand_id/models.json
  def create
    @model = Model.new(model_params)
    @model.brand_id = params[:brand_id]

    respond_to do |format|
      if @model.save
        format.html { redirect_to brand_model_path(@model.brand, @model), notice: "Model was successfully created." }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/:brand_id/models/1 or /brands/:brand_id/models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to brand_model_path(@model.brand, @model), notice: "Model was successfully updated." }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/:brand_id/models/1 or /brands/:brand_id/models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to brand_models_path(@model.brand), notice: "Model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_model
    @model = Model.find(params[:id])
  end

  def set_brand
    @brand = Brand.find(params[:brand_id])
  end

  def model_params
    params.require(:model).permit(:name, :year)
  end

  def user_only
    redirect_to(root_path, alert: "Not authorized") unless user_signed_in?
  end

  def admin_only
    if current_user.nil? || !current_user.admin?
      redirect_to(root_path, alert: "Not authorized")
    end
  end
end

app/helpers/admin/models_helper.rb
module Admin::ModelsHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.html.erb
<!-- app/views/admin/models/_form.html.erb -->
<%= form_with(model: [@brand, @model], local: true) do |form| %>
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
        <% @model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :year %>
    <%= form.number_field :year, class: 'form-control' %>
  </div>
  <br>
  <div class="form-group">
    <%= form.submit class: 'btn btn-primary mb-3' %>
  </div>
<% end %>

app/views/models/edit.html.erb
<!-- app/views/models/edit.html.erb -->
<h1>Edit Model</h1>

<%= render 'form', model: @model %>

<%= link_to 'Back to Models', brand_path(@model.brand), class: 'btn btn-secondary' %>

app/views/models/new.html.erb
<!-- app/views/models/new.html.erb -->
<h1>New Model</h1>

<%= render 'form', model: @model %>

<%= link_to 'Back to Models', brand_path(@brand), class: 'btn btn-secondary' %>

app/views/models/show.html.erb
<!-- app/views/models/show.html.erb -->
<h1>Model</h1>
<br>
<h3><%= "Model name: #{@model.name}" %></h1>
<h3><%= "Year of Production: #{@model.year}" %></h2>
<br>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_brand_model_path(@model.brand, @model), class: 'btn btn-warning' %>
<% end %>
<%= link_to 'Back to Models', brand_path(@model.brand), class: 'btn btn-secondary' %>