config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "dashboard#index"
    resources :brands, only: [ :index, :new, :create, :destroy ] do
      resources :models, only: [ :new, :create, :destroy ]
      collection do
        delete "delete_all"
      end
    end
  end

  resources :brands do
    resources :models
  end

  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  root "brands#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < ApplicationController
    before_action :authenticate_user!
    before_action :admin_only

    def index
      @brands = Brand.includes(:models).all
      @brand = Brand.new
      @model = Model.new
    end

    private

    def admin_only
      if current_user.nil? || !current_user.admin?
        redirect_to(root_path, alert: "Not authorized")
      end
    end
  end
end

app/views/admin/dashboard/index.html.erb
<h1>Admin Panel</h1>

<div class="button-container">
  <%= link_to 'Import Data', '#', class: 'btn btn-primary mb-3' %>
  <%= button_to 'Delete Data', delete_all_admin_brands_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mb-3' %>
</div>

<%= link_to 'New Brand', new_admin_brand_path, class: 'btn btn-primary mb-3', style: 'background-color: #17B169;' %>

<table class="table">
  <thead>
    <tr>
      <th>Brand and Modeles</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td>
          <div class="button-container">
            <%= button_to 'Delete Brand', admin_brand_path(brand), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <%= link_to 'Add Model', new_admin_brand_model_path(brand), class: 'btn btn-primary' %>
          </div>
        </td>
      </tr>
      <% if brand.models.any? %>
        <% brand.models.each do |model| %>
          <tr>
            <td style="padding-left: 40px;">&bull; <%= model.name %></td>
            <td>
              <%= button_to 'Delete Model', admin_brand_model_path(brand, model), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            </td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>